### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by hrqmonteiro** [evprkr/galaxian-vim#4]
![print2](https://user-images.githubusercontent.com/17055027/124396598-e18f9300-dce0-11eb-8186-6687356cbb94.png)

I tried using Packer and installing it manually. Doesn't work on termguicolors or without.

**Comment by leftbones** [comment]
I don’t personally use Packer, but I’ll give it a go and see if I can fix it. Otherwise, manual installation is super easy.

**Comment by leftbones** [comment]
I just now realized you said you tried installing manually.

Based on your pictures, it _looks_ like you've installed it correctly. However, syntax highlighting is only really optimized for Python since that's mostly all that I use, so you're not getting all of the colors.

If you want to have a go at making it work better for Lua, I'll gladly accept any pull requests.
